// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHHVZiG3__g0etZ-_RPmAjuF0e2i102WM',
    appId: '1:547912729872:web:5f98ffac520ff32ad19195',
    messagingSenderId: '547912729872',
    projectId: 'flutter-student-database-6df07',
    authDomain: 'flutter-student-database-6df07.firebaseapp.com',
    storageBucket: 'flutter-student-database-6df07.firebasestorage.app',
    measurementId: 'G-YQ71J79Z7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArp2_GBdzNaCm4bGkI5HzLuPxEHzJcfTk',
    appId: '1:547912729872:android:8570102bc71b4430d19195',
    messagingSenderId: '547912729872',
    projectId: 'flutter-student-database-6df07',
    storageBucket: 'flutter-student-database-6df07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFd-B4cETztE1jrvA8ceZnFLKsoMtw_n0',
    appId: '1:547912729872:ios:7726ea0d00ecaa13d19195',
    messagingSenderId: '547912729872',
    projectId: 'flutter-student-database-6df07',
    storageBucket: 'flutter-student-database-6df07.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFd-B4cETztE1jrvA8ceZnFLKsoMtw_n0',
    appId: '1:547912729872:ios:7726ea0d00ecaa13d19195',
    messagingSenderId: '547912729872',
    projectId: 'flutter-student-database-6df07',
    storageBucket: 'flutter-student-database-6df07.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHHVZiG3__g0etZ-_RPmAjuF0e2i102WM',
    appId: '1:547912729872:web:bb576b2b9011b592d19195',
    messagingSenderId: '547912729872',
    projectId: 'flutter-student-database-6df07',
    authDomain: 'flutter-student-database-6df07.firebaseapp.com',
    storageBucket: 'flutter-student-database-6df07.firebasestorage.app',
    measurementId: 'G-BE01XSZB86',
  );
}
